# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:             [ROLE_ADMIN]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                csrf_token_generator: security.csrf.token_manager
                default_target_path: security_redirect

            access_denied_handler: AppBundle\EventListener\FOSUserBundle\AccessDeniedHandler

    access_control:
        #Role admin
        #        - { path:     ^/, roles: [ ROLE_ADMIN ] }
        #        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # La página de inicio es accesible para cualquier rol, siempre que se esté autenticado
        - { path: ^/admin/inicio,
            role: IS_AUTHENTICATED_FULLY }
        - { path: ^/[0-9a-zA-Z\-]+/inscripcion,
            role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin,
            role: ROLE_ADMIN }
        - { path: ^/,
            role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
