<?php
namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\Localidad;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;


class LocalidadFixture extends Fixture implements FixtureInterface, DependentFixtureInterface
{

    public function load(ObjectManager $manager)
    {
        $localidades = array(
            array('l_distrito'=>'490','l_nom_dis'=> 'NICANOR MOLINAS','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'501','l_nom_dis'=> 'SALADERO CABAL','l_departamento'=> '35','l_nom_dpto'=> 'GARAY','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'620','l_nom_dis'=> 'ARMSTRONG','l_departamento'=> '7','l_nom_dpto'=> 'BELGRANO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'621','l_nom_dis'=> 'BOUQUET','l_departamento'=> '7','l_nom_dpto'=> 'BELGRANO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'622','l_nom_dis'=> 'LAS PAREJAS','l_departamento'=> '7','l_nom_dpto'=> 'BELGRANO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'623','l_nom_dis'=> 'LAS ROSAS','l_departamento'=> '7','l_nom_dpto'=> 'BELGRANO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'624','l_nom_dis'=> 'MONTES DE OCA','l_departamento'=> '7','l_nom_dpto'=> 'BELGRANO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'625','l_nom_dis'=> 'TORTUGAS','l_departamento'=> '7','l_nom_dpto'=> 'BELGRANO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'627','l_nom_dis'=> 'AREQUITO','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'628','l_nom_dis'=> 'ARTEAGA','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'629','l_nom_dis'=> 'BERAVEBU','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'630','l_nom_dis'=> 'BIGAND','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'631','l_nom_dis'=> 'CASILDA','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'632','l_nom_dis'=> 'CHABAS','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'633','l_nom_dis'=> 'CHAÑAR LADEADO','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'634','l_nom_dis'=> 'GODEKEN','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'635','l_nom_dis'=> 'LOS MOLINOS','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'636','l_nom_dis'=> 'LOS QUIRQUINCHOS','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'637','l_nom_dis'=> 'SANFORD','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'638','l_nom_dis'=> 'SAN JOSE DE LA ESQUINA','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'639','l_nom_dis'=> 'VILLADA','l_departamento'=> '14','l_nom_dpto'=> 'CASEROS','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'641','l_nom_dis'=> 'ANGELICA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'642','l_nom_dis'=> 'ATALIVA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'643','l_nom_dis'=> 'AURELIA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'644','l_nom_dis'=> 'BAUER Y SIGEL','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'645','l_nom_dis'=> 'BELLA ITALIA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'646','l_nom_dis'=> 'CASTELLANOS','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'647','l_nom_dis'=> 'COLONIA ALDAO','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'648','l_nom_dis'=> 'COLONIA BICHA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'649','l_nom_dis'=> 'BIGAND','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'650','l_nom_dis'=> 'COLONIA CELLO','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'651','l_nom_dis'=> 'TACURAL','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'652','l_nom_dis'=> 'COLONIA ITURRASPE','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'653','l_nom_dis'=> 'COLONIA MARGARITA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'654','l_nom_dis'=> 'COLONIA RAQUEL','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'655','l_nom_dis'=> 'TACURALES','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'656','l_nom_dis'=> 'CORONEL FRAGA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'657','l_nom_dis'=> 'EGUSQUIZA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'658','l_nom_dis'=> 'ESMERALDA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'659','l_nom_dis'=> 'ESTACION CLUCELLAS','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'660','l_nom_dis'=> 'EUSEBIA Y CAROLINA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'661','l_nom_dis'=> 'EUSTOLIA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'662','l_nom_dis'=> 'FIDELA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'663','l_nom_dis'=> 'FRONTERA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'664','l_nom_dis'=> 'GALISTEO','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'665','l_nom_dis'=> 'GARIBALDI','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'666','l_nom_dis'=> 'HUGENTOBLER','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'667','l_nom_dis'=> 'HUMBERTO PRIMO','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'668','l_nom_dis'=> 'JOSEFINA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'669','l_nom_dis'=> 'LEHMANN','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'670','l_nom_dis'=> 'MARIA JUANA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'671','l_nom_dis'=> 'MAUA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'672','l_nom_dis'=> 'PLAZA CLUCELLAS','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'673','l_nom_dis'=> 'PRESIDENTE ROCA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'674','l_nom_dis'=> 'PUEBLO MARINI','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'675','l_nom_dis'=> 'RAFAELA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'676','l_nom_dis'=> 'RAMONA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'677','l_nom_dis'=> 'SAGUIER','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'678','l_nom_dis'=> 'SAN ANTONIO','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'679','l_nom_dis'=> 'SANTA CLARA DE SAGUIER','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'680','l_nom_dis'=> 'SAN VICENTE','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'681','l_nom_dis'=> 'SUNCHALES','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'682','l_nom_dis'=> 'SUSANA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'683','l_nom_dis'=> 'VILA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'684','l_nom_dis'=> 'VILLA SAN JOSE','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'685','l_nom_dis'=> 'VIRGINIA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'686','l_nom_dis'=> 'ZENON PEREYRA','l_departamento'=> '21','l_nom_dpto'=> 'CASTELLANOS','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'688','l_nom_dis'=> 'ALCORTA','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'689','l_nom_dis'=> 'BOMBAL','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'690','l_nom_dis'=> 'CAÑADA RICA','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'691','l_nom_dis'=> 'CEPEDA','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'692','l_nom_dis'=> 'EMPALME VILLA CONSTITUCION','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'693','l_nom_dis'=> 'GENERAL GELLY','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'694','l_nom_dis'=> 'GODOY','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'695','l_nom_dis'=> 'JUAN B. MOLINA','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'696','l_nom_dis'=> 'JUNCAL','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'697','l_nom_dis'=> 'LA VANGUARDIA','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'698','l_nom_dis'=> 'MAXIMO PAZ','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'699','l_nom_dis'=> 'PAVON ARRIBA','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'700','l_nom_dis'=> 'PEYRANO','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'701','l_nom_dis'=> 'RUEDA','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'702','l_nom_dis'=> 'SANTA TERESA','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'703','l_nom_dis'=> 'SARGENTO CABRAL','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'704','l_nom_dis'=> 'THEOBALD','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'705','l_nom_dis'=> 'VILLA CONSTITUCION','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'706','l_nom_dis'=> 'PAVON','l_departamento'=> '28','l_nom_dpto'=> 'CONSTITUCION','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'707','l_nom_dis'=> 'CAYASTA','l_departamento'=> '35','l_nom_dpto'=> 'GARAY','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'708','l_nom_dis'=> 'HELVECIA','l_departamento'=> '35','l_nom_dpto'=> 'GARAY','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'709','l_nom_dis'=> 'SANTA ROSA DE CALCHINES','l_departamento'=> '35','l_nom_dpto'=> 'GARAY','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'710','l_nom_dis'=> 'COLONIA MASCIAS','l_departamento'=> '35','l_nom_dpto'=> 'GARAY','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'711','l_nom_dis'=> 'AARON CASTELLANOS','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'712','l_nom_dis'=> 'AMENABAR','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'713','l_nom_dis'=> 'CAFFERATA','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'714','l_nom_dis'=> 'CAÑADA DEL UCLE','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'715','l_nom_dis'=> 'CARMEN','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'716','l_nom_dis'=> 'CARRERAS','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'717','l_nom_dis'=> 'CHAPUY','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'718','l_nom_dis'=> 'MURPHY','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'719','l_nom_dis'=> 'CHOVET','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'720','l_nom_dis'=> 'CHRISTOPHERSEN','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'721','l_nom_dis'=> 'DIEGO DE ALVEAR','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'722','l_nom_dis'=> 'ELORTONDO','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'723','l_nom_dis'=> 'FIRMAT','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'724','l_nom_dis'=> 'HUGHES','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'725','l_nom_dis'=> 'LABORDEBOY','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'726','l_nom_dis'=> 'LA CHISPA','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'727','l_nom_dis'=> 'LAZZARINO','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'728','l_nom_dis'=> 'MAGGIOLO','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'729','l_nom_dis'=> 'MARIA TERESA','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'730','l_nom_dis'=> 'MELINCUE','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'731','l_nom_dis'=> 'MIGUEL TORRES','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'732','l_nom_dis'=> 'RUFINO','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'733','l_nom_dis'=> 'SANCTI SPIRITU','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'734','l_nom_dis'=> 'SAN EDUARDO','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'735','l_nom_dis'=> 'SAN FRANCISCO DE SANTA FE','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'736','l_nom_dis'=> 'SAN GREGORIO','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'737','l_nom_dis'=> 'SANTA ISABEL','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'738','l_nom_dis'=> 'TEODELINA','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'739','l_nom_dis'=> 'VENADO TUERTO','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'740','l_nom_dis'=> 'VILLA CAÑAS','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'741','l_nom_dis'=> 'WHEELWRIGHT','l_departamento'=> '42','l_nom_dpto'=> 'GENERAL LOPEZ','nodo'=> 'VENADO TUERTO'),
            array('l_distrito'=>'742','l_nom_dis'=> 'GUADALUPE NORTE','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'743','l_nom_dis'=> 'AVELLANEDA','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'744','l_nom_dis'=> 'ARROYO CEIBAL','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'745','l_nom_dis'=> 'BERNA','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'746','l_nom_dis'=> 'MALABRIGO','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'747','l_nom_dis'=> 'FLORENCIA','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'748','l_nom_dis'=> 'GARABATO','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'749','l_nom_dis'=> 'GOLONDRINA','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'750','l_nom_dis'=> 'CAÑADA OMBU','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'751','l_nom_dis'=> 'INGENIERO CHANOURDIE','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'752','l_nom_dis'=> 'INTIYACO','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'753','l_nom_dis'=> 'LANTERI','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'754','l_nom_dis'=> 'LAS GARZAS','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'755','l_nom_dis'=> 'EL SOMBRERITO','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'756','l_nom_dis'=> 'LAS TOSCAS','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'757','l_nom_dis'=> 'EL RABON','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'758','l_nom_dis'=> 'LOS AMORES','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'759','l_nom_dis'=> 'RECONQUISTA','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'760','l_nom_dis'=> 'LOS LAURELES','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'761','l_nom_dis'=> 'SAN ANTONIO DE OBLIGADO','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'762','l_nom_dis'=> 'TACUARENDI','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'763','l_nom_dis'=> 'TARTAGAL','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'764','l_nom_dis'=> 'VILLA ANA','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'765','l_nom_dis'=> 'VILLA GUILLERMINA','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'766','l_nom_dis'=> 'VILLA OCAMPO','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'767','l_nom_dis'=> 'EL ARAZA','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'768','l_nom_dis'=> 'LA SARITA','l_departamento'=> '49','l_nom_dpto'=> 'GENERAL OBLIGADO','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'769','l_nom_dis'=> 'PUEBLO ANDINO','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'770','l_nom_dis'=> 'BUSTINZA','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'771','l_nom_dis'=> 'CAÑADA DE GOMEZ','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'772','l_nom_dis'=> 'CARRIZALES','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'773','l_nom_dis'=> 'CLASSON','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'774','l_nom_dis'=> 'CORREA','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'775','l_nom_dis'=> 'SALTO GRANDE','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'776','l_nom_dis'=> 'LUCIO V. LOPEZ','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'777','l_nom_dis'=> 'OLIVEROS','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'778','l_nom_dis'=> 'TOTORAS','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'779','l_nom_dis'=> 'SERODINO','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'780','l_nom_dis'=> 'VILLA ELOISA','l_departamento'=> '56','l_nom_dpto'=> 'IRIONDO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'782','l_nom_dis'=> 'ARROYO AGUIAR','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'783','l_nom_dis'=> 'CABAL','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'784','l_nom_dis'=> 'CANDIOTI','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'785','l_nom_dis'=> 'EMILIA','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'786','l_nom_dis'=> 'LAGUNA PAIVA','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'787','l_nom_dis'=> 'LLAMBI CAMPBELL','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'788','l_nom_dis'=> 'MONTE VERA','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'789','l_nom_dis'=> 'NELSON','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'790','l_nom_dis'=> 'RECREO','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'791','l_nom_dis'=> 'CAMPO ANDINO','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'792','l_nom_dis'=> 'SANTA FE','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'793','l_nom_dis'=> 'SANTO TOME','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'794','l_nom_dis'=> 'SAUCE VIEJO','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'795','l_nom_dis'=> 'ARROYO LEYES','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'796','l_nom_dis'=> 'SAN JOSE DEL RINCON','l_departamento'=> '63','l_nom_dpto'=> 'LA CAPITAL','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'797','l_nom_dis'=> 'CAVOUR','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'798','l_nom_dis'=> 'CULULU','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'799','l_nom_dis'=> 'ELISA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'800','l_nom_dis'=> 'EMPALME SAN CARLOS','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'801','l_nom_dis'=> 'ESPERANZA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'802','l_nom_dis'=> 'FELICIA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'803','l_nom_dis'=> 'FRANCK','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'804','l_nom_dis'=> 'GRUTLY','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'805','l_nom_dis'=> 'HIPATIA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'806','l_nom_dis'=> 'HUMBOLDT','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'807','l_nom_dis'=> 'ITUZAINGO','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'808','l_nom_dis'=> 'JACINTO L. ARAUZ','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'809','l_nom_dis'=> 'LA PELADA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'810','l_nom_dis'=> 'LAS TUNAS','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'811','l_nom_dis'=> 'MARIA LUISA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'812','l_nom_dis'=> 'MATILDE','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'813','l_nom_dis'=> 'NUEVO TORINO','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'814','l_nom_dis'=> 'PILAR','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'815','l_nom_dis'=> 'PROGRESO','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'816','l_nom_dis'=> 'PROVIDENCIA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'817','l_nom_dis'=> 'PUJATO NORTE','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'818','l_nom_dis'=> 'RIVADAVIA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'819','l_nom_dis'=> 'SA PEREYRA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'820','l_nom_dis'=> 'SAN AGUSTIN','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'821','l_nom_dis'=> 'SAN CARLOS CENTRO','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'822','l_nom_dis'=> 'SAN CARLOS NORTE','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'823','l_nom_dis'=> 'SAN CARLOS SUD','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'824','l_nom_dis'=> 'SAN JERONIMO DEL SAUCE','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'825','l_nom_dis'=> 'SAN JERONIMO NORTE','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'826','l_nom_dis'=> 'SAN JOSE','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'827','l_nom_dis'=> 'SAN MARIANO','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'828','l_nom_dis'=> 'SANTA CLARA DE BUENA VISTA','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'829','l_nom_dis'=> 'SANTA MARIA CENTRO','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'830','l_nom_dis'=> 'SANTA MARIA NORTE','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'831','l_nom_dis'=> 'SANTO DOMINGO','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'832','l_nom_dis'=> 'SARMIENTO','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'833','l_nom_dis'=> 'SOUTOMAYOR','l_departamento'=> '70','l_nom_dpto'=> 'LAS COLONIAS','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'834','l_nom_dis'=> 'SAN BERNARDO','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'835','l_nom_dis'=> 'ESTEBAN RAMS','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'836','l_nom_dis'=> 'JUAN DE GARAY','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'837','l_nom_dis'=> 'LOGRONO','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'838','l_nom_dis'=> 'GREGORIA PEREZ DE DENIS','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'839','l_nom_dis'=> 'MONTEFIORE','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'840','l_nom_dis'=> 'VILLA MINETTI','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'841','l_nom_dis'=> 'POZO BORRADO','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'842','l_nom_dis'=> 'SANTA MARGARITA','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'843','l_nom_dis'=> 'GATO COLORADO','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'844','l_nom_dis'=> 'TOSTADO','l_departamento'=> '77','l_nom_dpto'=> '9 DE JULIO','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'846','l_nom_dis'=> 'ACEBAL','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'847','l_nom_dis'=> 'ALBARELLOS','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'848','l_nom_dis'=> 'ALVAREZ','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'849','l_nom_dis'=> 'ALVEAR','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'850','l_nom_dis'=> 'ARMINDA','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'851','l_nom_dis'=> 'ARROYO SECO','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'852','l_nom_dis'=> 'CARMEN DEL SAUCE','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'853','l_nom_dis'=> 'CORONEL RODOLFO DOMINGUEZ','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'854','l_nom_dis'=> 'FIGHIERA','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'855','l_nom_dis'=> 'FUNES','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'856','l_nom_dis'=> 'GRANADERO BAIGORRIA','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'857','l_nom_dis'=> 'IBARLUCEA','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'858','l_nom_dis'=> 'PEREZ','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'859','l_nom_dis'=> 'PINERO','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'860','l_nom_dis'=> 'PUEBLO ESTHER','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'861','l_nom_dis'=> 'PUEBLO MUNOZ','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'862','l_nom_dis'=> 'CORONEL BOGADO','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'863','l_nom_dis'=> 'ROSARIO','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'865','l_nom_dis'=> 'SOLDINI','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'866','l_nom_dis'=> 'URANGA','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'867','l_nom_dis'=> 'VILLA AMELIA','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'868','l_nom_dis'=> 'VILLA GOBERNADOR GALVEZ','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'869','l_nom_dis'=> 'ZAVALLA','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'870','l_nom_dis'=> 'GENERAL LAGOS','l_departamento'=> '84','l_nom_dpto'=> 'ROSARIO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'871','l_nom_dis'=> 'AGUARA GRANDE','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'872','l_nom_dis'=> 'AMBROSETTI','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'873','l_nom_dis'=> 'ARRUFO','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'874','l_nom_dis'=> 'CAPIVARA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'875','l_nom_dis'=> 'CERES','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'876','l_nom_dis'=> 'COLONIA ANA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'877','l_nom_dis'=> 'COLONIA BOSSI','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'878','l_nom_dis'=> 'COLONIA CLARA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'879','l_nom_dis'=> 'COLONIA ROSA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'880','l_nom_dis'=> 'CONSTANZA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'881','l_nom_dis'=> 'CURUPAYTI','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'882','l_nom_dis'=> 'DOS ROSAS Y LA LEGUA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'883','l_nom_dis'=> 'HERSILIA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'884','l_nom_dis'=> 'HUANQUEROS','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'885','l_nom_dis'=> 'LA LUCILA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'886','l_nom_dis'=> 'LA RUBIA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'887','l_nom_dis'=> 'LAS AVISPAS','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'888','l_nom_dis'=> 'LAS PALMERAS','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'889','l_nom_dis'=> 'MOISES VILLE','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'890','l_nom_dis'=> 'MONIGOTES','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'891','l_nom_dis'=> 'MONTE OSCURIDAD','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'892','l_nom_dis'=> 'NANDUCITA','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'893','l_nom_dis'=> 'PALACIOS','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'894','l_nom_dis'=> 'PORTUGALETE','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'895','l_nom_dis'=> 'SAN CRISTOBAL','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'896','l_nom_dis'=> 'SAN GUILLERMO','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'897','l_nom_dis'=> 'SANTURCE','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'898','l_nom_dis'=> 'SOLEDAD','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'899','l_nom_dis'=> 'SUARDI','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'900','l_nom_dis'=> 'VILLA SARALEGUI','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'901','l_nom_dis'=> 'VILLA TRINIDAD','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'902','l_nom_dis'=> 'LA CABRAL','l_departamento'=> '91','l_nom_dpto'=> 'SAN CRISTOBAL','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'903','l_nom_dis'=> 'ALEJANDRA','l_departamento'=> '98','l_nom_dpto'=> 'SAN JAVIER','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'904','l_nom_dis'=> 'CACIQUE ARIACAIQUIN','l_departamento'=> '98','l_nom_dpto'=> 'SAN JAVIER','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'905','l_nom_dis'=> 'ROMANG','l_departamento'=> '98','l_nom_dpto'=> 'SAN JAVIER','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'906','l_nom_dis'=> 'COLONIA DURAN','l_departamento'=> '98','l_nom_dpto'=> 'SAN JAVIER','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'907','l_nom_dis'=> 'SAN JAVIER','l_departamento'=> '98','l_nom_dpto'=> 'SAN JAVIER','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'908','l_nom_dis'=> 'LA BRAVA','l_departamento'=> '98','l_nom_dpto'=> 'SAN JAVIER','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'909','l_nom_dis'=> 'COLONIA TERESA','l_departamento'=> '98','l_nom_dpto'=> 'SAN JAVIER','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'910','l_nom_dis'=> 'AROCENA','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'911','l_nom_dis'=> 'BARRANCAS','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'912','l_nom_dis'=> 'BERNARDO DE IRIGOYEN','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'913','l_nom_dis'=> 'CAMPO PIAGGIO','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'914','l_nom_dis'=> 'CASALEGNO','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'915','l_nom_dis'=> 'CENTENO','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'916','l_nom_dis'=> 'CORONDA','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'917','l_nom_dis'=> 'DESVIO ARIJON','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'918','l_nom_dis'=> 'DIAZ','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'919','l_nom_dis'=> 'GABOTO','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'920','l_nom_dis'=> 'GALVEZ','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'921','l_nom_dis'=> 'GESSLER','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'922','l_nom_dis'=> 'IRIGOYEN','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'923','l_nom_dis'=> 'LARRECHEA','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'924','l_nom_dis'=> 'LOMA ALTA','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'925','l_nom_dis'=> 'LOPEZ','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'926','l_nom_dis'=> 'MACIEL','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'927','l_nom_dis'=> 'SAN EUGENIO','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'928','l_nom_dis'=> 'SAN FABIAN','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'929','l_nom_dis'=> 'SAN GENARO','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'931','l_nom_dis'=> 'MONJE','l_departamento'=> '105','l_nom_dpto'=> 'SAN GERONIMO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'933','l_nom_dis'=> 'ANGELONI','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'934','l_nom_dis'=> 'CAYASTACITO','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'935','l_nom_dis'=> 'ESTHER','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'936','l_nom_dis'=> 'GOBERNADOR CRESPO','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'937','l_nom_dis'=> 'LA CRIOLLA','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'938','l_nom_dis'=> 'LA PENCA Y CARAGUATA','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'939','l_nom_dis'=> 'MARCELINO ESCALADA','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'940','l_nom_dis'=> 'NARE','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'941','l_nom_dis'=> 'PEDRO GOMEZ CELLO','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'942','l_nom_dis'=> 'RAMAYON','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'943','l_nom_dis'=> 'SAN BERNARDO','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'944','l_nom_dis'=> 'SAN JUSTO','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'945','l_nom_dis'=> 'SAN MARTIN NORTE','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'946','l_nom_dis'=> 'VERA Y PINTADO','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'947','l_nom_dis'=> 'LA CAMILA','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'948','l_nom_dis'=> 'VIDELA','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'949','l_nom_dis'=> 'SILVA','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'950','l_nom_dis'=> 'COLONIA DOLORES','l_departamento'=> '112','l_nom_dpto'=> 'SAN JUSTO','nodo'=> 'SANTA FE'),
            array('l_distrito'=>'951','l_nom_dis'=> 'ALDAO','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'952','l_nom_dis'=> 'ROLDAN','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'953','l_nom_dis'=> 'CAPITAN BERMUDEZ','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'954','l_nom_dis'=> 'CARCARANA','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'955','l_nom_dis'=> 'CORONEL ARNOLD','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'956','l_nom_dis'=> 'FRAY LUIS BELTRAN','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'957','l_nom_dis'=> 'FUENTES','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'958','l_nom_dis'=> 'TIMBUES','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'959','l_nom_dis'=> 'LUIS PALACIOS','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'960','l_nom_dis'=> 'PUERTO GENERAL SAN MARTIN','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'961','l_nom_dis'=> 'PUJATO','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'962','l_nom_dis'=> 'RICARDONE','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'963','l_nom_dis'=> 'SAN JERONIMO SUD','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'964','l_nom_dis'=> 'SAN LORENZO','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'965','l_nom_dis'=> 'VILLA MUGUETA','l_departamento'=> '119','l_nom_dpto'=> 'SAN LORENZO','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'967','l_nom_dis'=> 'CANADA ROSQUIN','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'968','l_nom_dis'=> 'CARLOS PELLEGRINI','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'969','l_nom_dis'=> 'CASAS','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'970','l_nom_dis'=> 'CASTELAR','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'971','l_nom_dis'=> 'COLONIA BELGRANO','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'972','l_nom_dis'=> 'CRISPI','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'973','l_nom_dis'=> 'EL TREBOL','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'974','l_nom_dis'=> 'LANDETA','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'975','l_nom_dis'=> 'LAS BANDURRIAS','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'976','l_nom_dis'=> 'LAS PETACAS','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'977','l_nom_dis'=> 'LOS CARDOS','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'978','l_nom_dis'=> 'MARIA SUSANA','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'979','l_nom_dis'=> 'PIAMONTE','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'ROSARIO'),
            array('l_distrito'=>'980','l_nom_dis'=> 'SAN JORGE','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'981','l_nom_dis'=> 'SAN MARTIN DE LAS ESCOBAS','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'982','l_nom_dis'=> 'SASTRE','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'983','l_nom_dis'=> 'TRAILL','l_departamento'=> '126','l_nom_dpto'=> 'SAN MARTIN','nodo'=> 'RAFAELA'),
            array('l_distrito'=>'985','l_nom_dis'=> 'CALCHAQUI','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'986','l_nom_dis'=> 'VERA','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'987','l_nom_dis'=> 'TOBA','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'988','l_nom_dis'=> 'FORTIN OLMOS','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'989','l_nom_dis'=> 'MARGARITA','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA'),
            array('l_distrito'=>'990','l_nom_dis'=> 'LA GALLARETA','l_departamento'=> '133','l_nom_dpto'=> 'VERA','nodo'=> 'RECONQUISTA')
            // ...
        );
        foreach ($localidades as $localidad) {
            $entidad = new Localidad();
            $entidad->setLDistrito($localidad['l_distrito']);
            $entidad->setLNomDis($localidad['l_nom_dis']);
            $entidad->setLDepartamento($localidad['l_departamento']);
            $entidad->setLNomDpto($localidad['l_nom_dpto']);
            $entidad->setNodo($localidad['nodo']);
            $entidad->setProvincia($this->getReference('ProvSantaFe'));
            $manager->persist($entidad);
        }
        $manager->flush();

    }

    /**
     * This method must return an array of fixtures classes
     * on which the implementing class depends on
     *
     * @return class-string[]
     */
    public function getDependencies()
    {
        return [
            ProvinciaFixture::class,
        ];
    }
}
